#!/usr/bin/env node
// Generates every design-token artifact in the portfolio from tokens.json.
// Fails the build when a required contrast pair regresses, so a colour change
// cannot quietly drop a surface below WCAG AA.
//
//   node scripts/build-tokens.mjs           build
//   node scripts/build-tokens.mjs --check   verify the checked-in output matches

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sibling } from "./siblings.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");
const repo = resolve(pkg, "../../..");
const T = JSON.parse(readFileSync(join(pkg, "tokens.json"), "utf8"));
const checkOnly = process.argv.includes("--check");

const BANNER = (name) =>
  `/* GENERATED by web-kit/packages/brand/scripts/build-tokens.mjs from tokens.json.\n   Do not hand-edit ${name}. Change tokens.json and rebuild.\n   Contract: Infra/docs/UX-STANDARD.md */\n`;

/* ---------- colour maths ---------- */

const hexToRgb = (hex) => {
  const h = hex.replace("#", "");
  const n = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  return [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16));
};

const luminance = (hex) => {
  const [r, g, b] = hexToRgb(hex).map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

const contrast = (a, b) => {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
};

/* ---------- reference resolution ---------- */

// "{accent}.700" -> "#b45309" for a given theme; "base.white" -> "#ffffff"
// {accent2} is matched before {accent} so the longer placeholder wins.
function resolve_(ref, theme) {
  const filled = ref
    .replace("{accent2}", theme.accent2)
    .replace("{accent}", theme.accent)
    .replace("{neutral}", theme.neutral);
  const [group, step] = filled.split(".");
  if (group === "base") return T.base[step];
  const ramp = T.primitive[group];
  if (!ramp || !ramp[step]) throw new Error(`unresolvable token reference: ${ref} -> ${filled}`);
  return ramp[step];
}

const themeNames = Object.keys(T.themes).filter((k) => !k.startsWith("$"));
const roles = (mode) => Object.keys(T.semantic[mode]).filter((k) => !k.startsWith("$"));

function roleMap(themeName, mode) {
  const theme = T.themes[themeName];
  const out = {};
  for (const role of roles(mode)) out[role] = resolve_(T.semantic[mode][role], theme);
  return out;
}

// Gradients are written in terms of semantic roles, so each product gets its own
// for free from its accent pair. Longest role name first, so {accent-2-subtle}
// is not partially matched by {accent-2}.
function gradientMap(map) {
  const names = Object.keys(map).sort((a, b) => b.length - a.length);
  const out = {};
  for (const [name, tpl] of Object.entries(T.palette.gradient)) {
    if (name.startsWith("$")) continue;
    let s = tpl;
    for (const role of names) s = s.split(`{${role}}`).join(map[role]);
    out[name] = s;
  }
  return out;
}

/* ---------- contrast gate ---------- */

function auditContrast() {
  const failures = [];
  const rows = [];
  for (const themeName of themeNames) {
    for (const mode of ["light", "dark"]) {
      const m = roleMap(themeName, mode);
      for (const { fg, bg, min } of T.contrast.require) {
        const ratio = contrast(m[fg], m[bg]);
        const pass = ratio >= min;
        rows.push({ themeName, mode, fg, bg, fgHex: m[fg], bgHex: m[bg], ratio, min, pass });
        if (!pass) failures.push(`${themeName}/${mode}: ${fg} on ${bg} = ${ratio.toFixed(2)}:1 (needs ${min}:1) [${m[fg]} on ${m[bg]}]`);
      }
    }
  }
  return { rows, failures };
}

/* ---------- CSS ---------- */

const rampNames = Object.keys(T.primitive);

function tagSwatches() {
  const out = { light: [], dark: [] };
  for (const mode of ["light", "dark"]) {
    const d = T.palette.tag.derive[mode];
    for (const n of T.palette.tag.ramps) {
      const r = T.primitive[n];
      if (!r) throw new Error(`tag palette references unknown ramp: ${n}`);
      out[mode].push({ name: n, bg: r[d.bg], ink: r[d.ink], border: r[d.border] });
    }
  }
  return out;
}

// Asserts the derived tag swatches actually clear AA, since they are generated
// rather than hand-picked and a ramp change could silently break one.
function auditTags() {
  const failures = [];
  for (const mode of ["light", "dark"])
    for (const t of tagSwatches()[mode]) {
      const ratio = contrast(t.ink, t.bg);
      if (ratio < 4.5) failures.push(`tag/${mode}: ${t.name} ink ${t.ink} on ${t.bg} = ${ratio.toFixed(2)}:1 (needs 4.5:1)`);
    }
  return failures;
}

// The categorical palette is hand-picked, unlike the tag swatches, and nothing was
// checking it. That is how `--px-cat-8` shipped at 2.60:1 against white: a chart series
// nobody could see, in a palette whose whole job is telling series apart.
//
// 3:1 is the floor here, not 4.5:1. A series colour is a stroke, a fill or a legend
// swatch, which WCAG 1.4.11 treats as non-text. Anything that puts a cat colour on actual
// body text is misusing it. Every light surface in every theme is checked, not just the
// theme's own, because a chart can sit on `surface`, `bg` or a raised card, and
// `surface-raised` is pure white - the harshest of the three.
function auditCategorical() {
  const failures = [];
  for (const mode of ["light", "dark"]) {
    const surfaces = new Set();
    for (const themeName of themeNames) {
      const m = roleMap(themeName, mode);
      for (const role of ["bg", "surface", "surface-raised"]) surfaces.add(m[role]);
    }
    T.palette.categorical[mode].forEach((hex, i) => {
      for (const bg of surfaces) {
        const ratio = contrast(hex, bg);
        if (ratio < 3)
          failures.push(
            `categorical/${mode}: cat-${i + 1} ${hex} on ${bg} = ${ratio.toFixed(2)}:1 (needs 3:1)`,
          );
      }
    });
  }
  return failures;
}

/**
 * One product's accent pair, for use inside a different product's interface.
 *
 * The app store lists three products on one page, the marketing site previews all of them, and
 * an app switcher shows every product at once. None of those can express a foreign brand by
 * setting `data-brand`, because the generated dark blocks are
 * `[data-brand="x"][data-theme="dark"]` — both attributes on one element — so a card carrying
 * only `data-brand` would take that brand's *light* tokens while sitting on a dark page.
 *
 * The first attempt at the app store used the 600 step of each brand's ramp instead, on the
 * theory that a mid-tone reads on either background. Measured, 21 of 24 label placements failed
 * AA, the worst at 2.19:1: a 600 step is chosen to sit on light surfaces, and on a dark one it
 * is barely above the background. So these are mode-aware, taken from the brand's own resolved
 * accent for the current mode, and asserted against every surface in the portfolio rather than
 * only against that brand's own.
 */
function brandAccents(mode) {
  const out = [];
  for (const themeName of themeNames) {
    const m = roleMap(themeName, mode);
    out.push({
      brand: themeName,
      accent: m.accent,
      accent2: m["accent-2"],
      text: m["accent-text"],
      text2: m["accent-2-text"],
      ink: m["accent-ink"],
    });
  }
  return out;
}

/** Every declaration that depends on the mode but not on the brand. */
function modeColours(mode) {
  const L = [];
  T.palette.categorical[mode].forEach((hex, i) => L.push(`--px-cat-${i + 1}: ${hex};`));
  for (const t of tagSwatches()[mode]) {
    L.push(`--px-tag-${t.name}-bg: ${t.bg};`);
    L.push(`--px-tag-${t.name}-ink: ${t.ink};`);
    L.push(`--px-tag-${t.name}-border: ${t.border};`);
  }
  for (const b of brandAccents(mode)) {
    L.push(`--px-brand-${b.brand}: ${b.accent};`);
    L.push(`--px-brand-${b.brand}-2: ${b.accent2};`);
    L.push(`--px-brand-${b.brand}-text: ${b.text};`);
    L.push(`--px-brand-${b.brand}-2-text: ${b.text2};`);
    L.push(`--px-brand-${b.brand}-ink: ${b.ink};`);
  }
  return L;
}

// Checked against every theme's surfaces, not just the owning brand's, because the whole point
// of these names is that they appear somewhere else — and "somewhere else" includes a theme with
// a warm neutral, which is where the near misses live.
//
// The floors mirror the roles the values come from. `-text` is a label, so 4.5:1 on all four
// surfaces, which is the same promise `accent-text` makes inside its own theme. The unsuffixed
// pair is a fill for a gradient, a dot or a chip, so 3:1 — WCAG 1.4.11 for non-text. Asserting
// the fill at 4.5 was the first attempt and it failed seven ways, all of them colours that are
// perfectly legible as a gradient and were never going to carry text.
function auditBrandAccents() {
  const failures = [];
  for (const mode of ["light", "dark"]) {
    const surfaces = new Set();
    for (const themeName of themeNames) {
      const m = roleMap(themeName, mode);
      for (const role of ["bg", "surface", "surface-raised", "surface-sunken"]) surfaces.add(m[role]);
    }
    for (const b of brandAccents(mode))
      for (const [role, hex, min] of [
        ["", b.accent, 3],
        ["-2", b.accent2, 3],
        ["-text", b.text, 4.5],
        ["-2-text", b.text2, 4.5],
      ])
        for (const bg of surfaces) {
          const ratio = contrast(hex, bg);
          if (ratio < min)
            failures.push(
              `brand/${mode}: --px-brand-${b.brand}${role} ${hex} on ${bg} = ${ratio.toFixed(2)}:1 (needs ${min}:1)`,
            );
        }
  }
  return failures;
}

function buildCss() {
  const L = [BANNER("prabhix-tokens.css"), ""];

  L.push(":root {");
  L.push("  /* primitive ramps — never used directly in product code */");
  for (const ramp of rampNames)
    for (const [step, hex] of Object.entries(T.primitive[ramp]))
      if (step !== "$doc") L.push(`  --px-${ramp}-${step}: ${hex};`);

  L.push("", "  /* spacing */");
  for (const [k, v] of Object.entries(T.scale.space))
    if (k !== "$doc") L.push(`  --px-space-${k.replace(".", "\\.")}: ${v};`);

  L.push("", "  /* radius, borders, opacity */");
  for (const [k, v] of Object.entries(T.scale.radius)) if (k !== "$doc") L.push(`  --px-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.scale.borderWidth)) L.push(`  --px-border-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.scale.opacity)) L.push(`  --px-opacity-${k}: ${v};`);

  L.push("", "  /* z layers */");
  for (const [k, v] of Object.entries(T.scale.z)) if (k !== "$doc") L.push(`  --px-z-${k}: ${v};`);

  L.push("", "  /* motion — duration and easing are separate tokens */");
  for (const [k, v] of Object.entries(T.scale.duration)) L.push(`  --px-duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.scale.easing)) L.push(`  --px-ease-${kebab(k)}: ${v};`);

  L.push("", "  /* type roles — size, line-height, weight, tracking and family move together */");
  for (const [k, v] of Object.entries(T.scale.font)) L.push(`  --px-font-${k}: ${v};`);
  for (const [role, t] of Object.entries(T.scale.type)) {
    if (role === "$doc") continue;
    L.push(`  --px-text-${role}: ${t.size};`);
    L.push(`  --px-text-${role}--line-height: ${t.lineHeight};`);
    L.push(`  --px-text-${role}--font-weight: ${t.weight};`);
    L.push(`  --px-text-${role}--letter-spacing: ${t.tracking};`);
    L.push(`  --px-text-${role}--font-family: var(--px-font-${t.font});`);
  }

  L.push("", "  /* layout and breakpoints */");
  for (const [k, v] of Object.entries(T.scale.layout)) L.push(`  --px-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.scale.breakpoint)) L.push(`  --px-bp-${k}: ${v};`);

  L.push("", "  /* density — comfortable is the default; see [data-density] below */");
  for (const [k, v] of Object.entries(T.scale.density.comfortable)) L.push(`  --px-density-${kebab(k)}: ${v};`);
  L.push("}", "");

  L.push(`[data-density="compact"] {`);
  for (const [k, v] of Object.entries(T.scale.density.compact)) L.push(`  --px-density-${kebab(k)}: ${v};`);
  L.push("}", "");

  // Brand-independent colours: the categorical series, the tag swatches, and each product's
  // accent pair for use outside that product. All three vary by mode and by nothing else, so
  // they are emitted from one function into all three places a mode is decided — the light
  // default, the explicit [data-theme="dark"], and the system-preference block below.
  //
  // One function because they had drifted. The dark tag swatches were emitted only into the
  // explicit block, so a visitor on a system set to dark who had never touched a theme toggle
  // got the light swatches: pale `#ffe4e6` chips on a dark page, in every app that does not
  // write data-theme itself.
  L.push("/* categorical series, tag swatches and cross-brand accents */");
  L.push(":root {");
  L.push(...modeColours("light").map((l) => `  ${l}`));
  L.push("}", "");
  L.push(`[data-theme="dark"] {`);
  L.push(...modeColours("dark").map((l) => `  ${l}`));
  L.push("}", "");

  // Semantic roles per brand. Default brand is technologies; at equal specificity later blocks win,
  // so brand-specific blocks must follow the :root default.
  for (const mode of ["light", "dark"]) {
    for (const themeName of themeNames) {
      const map = roleMap(themeName, mode);
      const isDefault = themeName === "technologies";
      let selector;
      if (mode === "light") {
        selector = isDefault ? `:root,\n[data-brand="${themeName}"]` : `[data-brand="${themeName}"]`;
      } else {
        selector = isDefault
          ? `[data-theme="dark"],\n[data-brand="${themeName}"][data-theme="dark"]`
          : `[data-brand="${themeName}"][data-theme="dark"]`;
      }
      L.push(`/* ${T.themes[themeName].label} — ${mode} — accent ${T.themes[themeName].accent} + ${T.themes[themeName].accent2} */`);
      L.push(`${selector} {`);
      for (const [role, hex] of Object.entries(map)) L.push(`  --px-${role}: ${hex};`);
      for (const [k, v] of Object.entries(T.scale.elevation[mode])) L.push(`  --px-elevation-${k}: ${v};`);
      for (const [k, v] of Object.entries(gradientMap(map))) L.push(`  --px-gradient-${k}: ${v};`);
      L.push("}", "");
    }
  }

  // system preference, only when no explicit data-theme is set
  L.push("@media (prefers-color-scheme: dark) {");
  for (const themeName of themeNames) {
    const map = roleMap(themeName, "dark");
    const sel = themeName === "technologies"
      ? `  :root:not([data-theme]),\n  [data-brand="${themeName}"]:not([data-theme])`
      : `  [data-brand="${themeName}"]:not([data-theme])`;
    L.push(`${sel} {`);
    for (const [role, hex] of Object.entries(map)) L.push(`    --px-${role}: ${hex};`);
    for (const [k, v] of Object.entries(T.scale.elevation.dark)) L.push(`    --px-elevation-${k}: ${v};`);
    for (const [k, v] of Object.entries(gradientMap(map))) L.push(`    --px-gradient-${k}: ${v};`);
    L.push("  }");
  }
  L.push("  :root:not([data-theme]) {");
  L.push(...modeColours("dark").map((l) => `    ${l}`));
  L.push("  }");
  L.push("}", "");

  L.push("@media (prefers-reduced-motion: reduce) {", "  :root {");
  for (const k of Object.keys(T.scale.duration)) L.push(`    --px-duration-${k}: 0ms;`);
  L.push("  }", "}", "");

  return L.join("\n");
}

/* ---------- Tailwind v4 preset ---------- */

function buildPreset() {
  const L = [BANNER("tailwind-preset.css"), ""];
  L.push(`@import "./prabhix-tokens.css";`, "");
  L.push("/* Every app imports this one file and never redefines a colour. */");
  L.push("@theme {");

  L.push("  /* semantic colours — resolve to the active [data-brand] and [data-theme] */");
  for (const role of roles("light")) L.push(`  --color-${role}: var(--px-${role});`);

  L.push("", "  /* primitive ramps, for the rare deliberate case */");
  for (const ramp of rampNames)
    for (const step of Object.keys(T.primitive[ramp]))
      if (step !== "$doc") L.push(`  --color-${ramp}-${step}: var(--px-${ramp}-${step});`);

  L.push("", "  /* categorical and tag */");
  T.palette.categorical.light.forEach((_, i) => L.push(`  --color-cat-${i + 1}: var(--px-cat-${i + 1});`));
  for (const t of tagSwatches().light) {
    L.push(`  --color-tag-${t.name}-bg: var(--px-tag-${t.name}-bg);`);
    L.push(`  --color-tag-${t.name}-ink: var(--px-tag-${t.name}-ink);`);
    L.push(`  --color-tag-${t.name}-border: var(--px-tag-${t.name}-border);`);
  }

  L.push("", "  /* spacing */");
  for (const k of Object.keys(T.scale.space))
    if (k !== "$doc") L.push(`  --spacing-${k}: var(--px-space-${k.replace(".", "\\.")});`);

  L.push("", "  /* radius and elevation */");
  for (const k of Object.keys(T.scale.radius)) if (k !== "$doc") L.push(`  --radius-${k}: var(--px-radius-${k});`);
  for (const k of Object.keys(T.scale.elevation.light)) L.push(`  --shadow-e${k}: var(--px-elevation-${k});`);

  L.push("", "  /* type */");
  for (const [k] of Object.entries(T.scale.font)) L.push(`  --font-${k}: var(--px-font-${k});`);
  for (const role of Object.keys(T.scale.type)) {
    if (role === "$doc") continue;
    L.push(`  --text-${role}: var(--px-text-${role});`);
    L.push(`  --text-${role}--line-height: var(--px-text-${role}--line-height);`);
    L.push(`  --text-${role}--font-weight: var(--px-text-${role}--font-weight);`);
    L.push(`  --text-${role}--letter-spacing: var(--px-text-${role}--letter-spacing);`);
  }

  L.push("", "  /* motion */");
  for (const k of Object.keys(T.scale.duration)) L.push(`  --animate-duration-${k}: var(--px-duration-${k});`);
  for (const k of Object.keys(T.scale.easing)) L.push(`  --ease-${kebab(k)}: var(--px-ease-${kebab(k)});`);

  // Literals, not var() references. Tailwind expands these namespaces inside @media and
  // @container preludes, where var() is not allowed and lightningcss rejects the output.
  L.push("", "  /* layout and breakpoints — literal, see note in build-tokens.mjs */");
  for (const [k, v] of Object.entries(T.scale.layout)) L.push(`  --container-${k.replace("container-", "")}: ${v};`);
  for (const [k, v] of Object.entries(T.scale.breakpoint)) L.push(`  --breakpoint-${k}: ${v};`);

  L.push("}", "");

  L.push("/* One focus treatment for the whole portfolio. */");
  L.push(":where(a, button, input, select, textarea, summary, [tabindex]):focus-visible {");
  L.push("  outline: var(--px-border-focus) solid var(--px-focus);");
  L.push("  outline-offset: 2px;");
  L.push("}", "");

  L.push("/* Gradients resolve to the active product's accent pair. */");
  for (const k of Object.keys(T.palette.gradient)) {
    if (k.startsWith("$")) continue;
    L.push(`.px-gradient-${k} { background-image: var(--px-gradient-${k}); }`);
  }
  L.push("");
  L.push(".px-gradient-text {");
  L.push("  background-image: var(--px-gradient-brand);");
  L.push("  -webkit-background-clip: text;");
  L.push("  background-clip: text;");
  L.push("  color: transparent;");
  L.push("}", "");
  return L.join("\n");
}

/* ---------- Dart ---------- */

const dartColor = (hex) => {
  if (hex === "transparent") return "Color(0x00000000)";
  const [r, g, b] = hexToRgb(hex);
  const to = (n) => n.toString(16).padStart(2, "0").toUpperCase();
  return `Color(0xFF${to(r)}${to(g)}${to(b)})`;
};

function buildDart() {
  const L = [];
  L.push("// GENERATED by web-kit/packages/brand/scripts/build-tokens.mjs from tokens.json.");
  L.push("// Do not hand-edit. Change tokens.json and rebuild.");
  L.push("// This file is why web and Flutter can no longer drift: both are this one source.");
  L.push("// Contract: Infra/docs/UX-STANDARD.md");
  L.push("");
  L.push("import 'dart:ui';");
  L.push("");
  L.push("/// One resolved colour role set for a product in one theme mode.");
  L.push("class PxColors {");
  const rs = roles("light");
  L.push("  const PxColors({");
  for (const r of rs) L.push(`    required this.${camel(r)},`);
  L.push("  });");
  L.push("");
  for (const r of rs) L.push(`  final Color ${camel(r)};`);
  L.push("");
  L.push("  /// Used by [ThemeExtension.lerp] so a theme change animates instead of snapping.");
  L.push("  PxColors lerpTo(PxColors other, double t) => PxColors(");
  for (const r of rs) L.push(`    ${camel(r)}: Color.lerp(${camel(r)}, other.${camel(r)}, t)!,`);
  L.push("  );");
  L.push("}");
  L.push("");

  L.push("/// Spacing, radius and type scales. Shared by every product, never overridden.");
  L.push("class PxSpace {");
  for (const [k, v] of Object.entries(T.scale.space))
    if (k !== "$doc") L.push(`  static const double s${k.replace(".", "_")} = ${parseFloat(v) || 0};`);
  L.push("}");
  L.push("");
  L.push("class PxRadius {");
  for (const [k, v] of Object.entries(T.scale.radius))
    if (k !== "$doc") L.push(`  static const double ${k} = ${parseFloat(v)};`);
  L.push("}");
  L.push("");
  L.push("class PxDuration {");
  for (const [k, v] of Object.entries(T.scale.duration))
    L.push(`  static const Duration ${camel(k)} = Duration(milliseconds: ${parseInt(v, 10)});`);
  L.push("}");
  L.push("");
  L.push("class PxType {");
  for (const [role, t] of Object.entries(T.scale.type)) {
    if (role === "$doc") continue;
    const px = t.size.endsWith("rem") ? parseFloat(t.size) * 16 : parseFloat(t.size);
    L.push(`  static const double ${camel(role)}Size = ${round(px)};`);
    L.push(`  static const double ${camel(role)}Height = ${t.lineHeight};`);
    L.push(`  static const int ${camel(role)}Weight = ${t.weight};`);
    L.push(`  static const double ${camel(role)}Tracking = ${round((parseFloat(t.tracking) || 0) * px)};`);
  }
  L.push("}");
  L.push("");

  for (const themeName of themeNames) {
    for (const mode of ["light", "dark"]) {
      const map = roleMap(themeName, mode);
      L.push(`/// ${T.themes[themeName].label} — ${mode}`);
      L.push(`const PxColors px${pascal(themeName)}${pascal(mode)} = PxColors(`);
      for (const [role, hex] of Object.entries(map)) L.push(`  ${camel(role)}: ${dartColor(hex)},`);
      L.push(");");
      L.push("");
    }
  }

  L.push("/// Every product theme, by the same key used by [data-brand] on the web.");
  L.push("const Map<String, ({PxColors light, PxColors dark})> pxThemes = {");
  for (const themeName of themeNames)
    L.push(`  '${themeName}': (light: px${pascal(themeName)}Light, dark: px${pascal(themeName)}Dark),`);
  L.push("};");
  L.push("");
  L.push("/// Categorical series colours for charts and generated avatars.");
  L.push(`const List<Color> pxCategoricalLight = [${T.palette.categorical.light.map(dartColor).join(", ")}];`);
  L.push(`const List<Color> pxCategoricalDark = [${T.palette.categorical.dark.map(dartColor).join(", ")}];`);
  L.push("");

  const tags = tagSwatches();
  L.push("/// One tinted label swatch: a fill, ink that clears 4.5:1 on that fill, and a hairline.");
  L.push("class PxTag {");
  L.push("  const PxTag(this.name, this.bg, this.ink, this.border);");
  L.push("  final String name;");
  L.push("  final Color bg;");
  L.push("  final Color ink;");
  L.push("  final Color border;");
  L.push("}");
  L.push("");
  L.push("/// The tinted label palette, in the same order as the web so a category that is");
  L.push("/// violet in a browser is violet in the app.");
  for (const mode of ["light", "dark"]) {
    L.push(`const List<PxTag> pxTag${pascal(mode)} = [`);
    for (const t of tags[mode])
      L.push(`  PxTag('${t.name}', ${dartColor(t.bg)}, ${dartColor(t.ink)}, ${dartColor(t.border)}),`);
    L.push("];");
    L.push("");
  }

  L.push("/// Picks a stable swatch for a piece of text — a sender, a label, a tenant — so the");
  L.push("/// same name is always the same colour, without storing a colour per record.");
  L.push("PxTag pxTagFor(String seed, {required bool dark}) {");
  L.push("  final palette = dark ? pxTagDark : pxTagLight;");
  L.push("  var hash = 0;");
  L.push("  for (final unit in seed.codeUnits) {");
  L.push("    hash = (hash * 31 + unit) & 0x1fffffff;");
  L.push("  }");
  L.push("  // Skips index 0, the neutral swatch, which is reserved for 'no category'.");
  L.push("  return palette[1 + hash % (palette.length - 1)];");
  L.push("}");
  L.push("");
  return L.join("\n");
}

/* ---------- reference doc ---------- */

function buildDoc(audit) {
  const L = [];
  L.push("# Design tokens — generated reference");
  L.push("");
  L.push("Generated from `tokens.json`. Do not edit. The contract these serve is");
  L.push("[UX-STANDARD.md](../../../Infra/docs/UX-STANDARD.md).");
  L.push("");
  L.push("## Product themes");
  L.push("");
  L.push("| Theme | `data-brand` | Accent ramp | Surface neutral | Default density |");
  L.push("|---|---|---|---|---|");
  for (const n of themeNames) {
    const t = T.themes[n];
    L.push(`| ${t.label} | \`${n}\` | ${t.accent} | ${t.neutral} | ${t.density} |`);
  }
  L.push("");
  L.push("Selecting a theme is one attribute on `<html>`:");
  L.push("");
  L.push("```html");
  L.push('<html data-brand="mobistack" data-theme="dark" data-density="compact">');
  L.push("```");
  L.push("");
  L.push(`## Contrast audit — ${audit.rows.length} assertions, ${audit.failures.length} failing`);
  L.push("");
  L.push("| Theme | Mode | Foreground | Background | Ratio | Min | |");
  L.push("|---|---|---|---|---:|---:|---|");
  for (const r of audit.rows)
    L.push(`| ${r.themeName} | ${r.mode} | \`${r.fg}\` ${r.fgHex} | \`${r.bg}\` ${r.bgHex} | ${r.ratio.toFixed(2)} | ${r.min} | ${r.pass ? "pass" : "**FAIL**"} |`);
  L.push("");
  L.push("`border` is intentionally not asserted: it draws decorative dividers. Every boundary that");
  L.push("identifies a control uses `border-strong`, which is asserted above at 3:1.");
  L.push("");
  return L.join("\n");
}

// The tag tone list and the seed-to-swatch rule, emitted for TypeScript as well as Dart.
// Both sides have to agree or the same sender is one colour in the browser and another in
// the app, so neither side gets to keep its own copy of the order.
function buildTagsTs() {
  const L = [BANNER("tags.ts").trimEnd(), ""];
  L.push("/** The generated tag tones, in palette order. Index 0 is the neutral 'no category' swatch. */");
  L.push("export const TAG_TONES = [");
  for (const n of T.palette.tag.ramps) L.push(`  "${n}",`);
  L.push("] as const;");
  L.push("");
  L.push("export type TagTone = (typeof TAG_TONES)[number];");
  L.push("");
  L.push("/**");
  L.push(" * Picks a stable swatch for a piece of text: a sender, a label, a tenant. The same");
  L.push(" * name is always the same colour, without storing a colour per record.");
  L.push(" *");
  L.push(" * Must stay identical to `pxTagFor` in prabhix_tokens.dart.");
  L.push(" */");
  L.push("export function toneFor(seed: string): TagTone {");
  L.push("  let hash = 0;");
  L.push("  for (let i = 0; i < seed.length; i += 1) {");
  L.push("    hash = (hash * 31 + seed.charCodeAt(i)) & 0x1fffffff;");
  L.push("  }");
  L.push("  // Skips index 0, the neutral swatch, which is reserved for 'no category'.");
  L.push("  return TAG_TONES[1 + (hash % (TAG_TONES.length - 1))];");
  L.push("}");
  L.push("");
  L.push("/**");
  L.push(" * The resolved hex for each swatch, for the few places that cannot use a CSS variable.");
  L.push(" *");
  L.push(" * Prefer `var(--px-tag-<tone>-bg)` and `-ink` everywhere you can: those follow the mode,");
  L.push(" * and these do not. This exists for values that leave the stylesheet — a colour written to");
  L.push(" * the database, an `<input type=\"color\">`, a third-party SDK that takes a hex string. Both");
  L.push(" * modes are given so a caller storing one can also show the other correctly.");
  L.push(" *");
  L.push(" * Every ink is asserted AA against its own bg by the contrast gate. Nothing is asserted");
  L.push(" * about an ink on any other background, so do not pair them across tones.");
  L.push(" */");
  L.push("export const TAG_SWATCHES: Record<");
  L.push("  \"light\" | \"dark\",");
  L.push("  Record<TagTone, { bg: string; ink: string; border: string }>");
  L.push("> = {");
  for (const mode of ["light", "dark"]) {
    L.push(`  ${mode}: {`);
    for (const t of tagSwatches()[mode]) {
      L.push(`    ${t.name}: { bg: "${t.bg}", ink: "${t.ink}", border: "${t.border}" },`);
    }
    L.push("  },");
  }
  L.push("};");
  L.push("");
  return L.join("\n");
}

/* ---------- helpers ---------- */

function kebab(s) { return s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase()); }
function camel(s) { return s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()); }
function pascal(s) { const c = camel(s); return c[0].toUpperCase() + c.slice(1); }
function round(n) { return Math.round(n * 100) / 100; }

/* ---------- write ---------- */

const audit = auditContrast();

// Each artifact names the repository that owns it. Everything outside web-kit is in a sibling
// repository, which only exists when the whole portfolio is checked out side by side; CI clones
// one repo at a time. Those targets are skipped there rather than reported as drift, because a
// check that fails on every CI run is a check people learn to ignore.
//
// The skip is announced, never silent. A run that quietly wrote fewer files than the author
// expected is exactly how Identity or Mobile ends up holding a stale copy of the tokens.
const artifacts = [
  ["web-kit", join(pkg, "prabhix-tokens.css"), buildCss()],
  ["web-kit", join(pkg, "tailwind-preset.css"), buildPreset()],
  ["web-kit", join(pkg, "TOKENS.md"), buildDoc(audit)],
  // Emitted into both packages on purpose. `brand` is where it belongs, because a tag
  // swatch is a token and every web app already depends on brand; `ui` gets a copy so it
  // stays installable without a nested file: dependency, which npm resolves from the
  // registry when a consuming app links ui by path. Two generated copies of one function
  // cannot drift; a hand-maintained re-export across a package boundary would.
  ["web-kit", join(pkg, "src/tags.ts"), buildTagsTs()],
  ["web-kit", sibling(repo, "web-kit/packages/ui/src/tags.ts"), buildTagsTs()],
  ["Mobile", sibling(repo, "Mobile/packages/prabhix_theme/lib/src/prabhix_tokens.dart"), buildDart()],
  ["Infra", sibling(repo, "Infra/design/prabhix-tokens.css"), buildCss()],
  // Served to the public by the app-store container, so it is a real surface and not a design
  // reference like the one above. It held a hand-written 68-line file that still described the
  // house cyan as the only accent and defined --px-house-* names nothing else has used for
  // months; generating it is the only way a page nobody opens while working stays current.
  ["Infra", sibling(repo, "Infra/deploy/app-store/www/assets/prabhix-tokens.css"), buildCss()],
  ["Identity", sibling(repo, "Identity/src/main/resources/static/assets/prabhix-tokens.css"), buildCss()],
];

/**
 * web-kit is this checkout; a sibling counts as present only if its directory exists - under
 * whatever case the clone arrived in, which on a runner is GitHub's spelling and not this
 * workspace's. See scripts/siblings.mjs.
 */
const present = (owner) => owner === "web-kit" || existsSync(sibling(repo, owner));

let drift = 0;
const skipped = new Set();
for (const [owner, path, body] of artifacts) {
  if (!present(owner)) {
    skipped.add(owner);
    continue;
  }
  if (checkOnly) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current !== body) {
      console.error(`drift: ${path.replace(repo, ".")} does not match tokens.json`);
      drift++;
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, "utf8");
  console.log(`wrote ${path.replace(repo, ".")}`);
}
if (skipped.size) {
  console.log(`\nskipped (repository not checked out here): ${[...skipped].sort().join(", ")}`);
}

const tagFailures = auditTags();
const catFailures = auditCategorical();
const brandFailures = auditBrandAccents();
const allFailures = [...audit.failures, ...tagFailures, ...catFailures, ...brandFailures];
if (allFailures.length) {
  console.error(`\ncontrast gate failed — ${allFailures.length} pair(s) below WCAG AA:\n`);
  for (const f of allFailures) console.error(`  ${f}`);
} else {
  console.log(
    `\ncontrast gate passed — ${audit.rows.length} role assertions across ${themeNames.length} themes x 2 modes, ` +
      `plus ${T.palette.tag.ramps.length * 2} tag swatches, ` +
      `${T.palette.categorical.light.length * 2} series colours ` +
      `and ${themeNames.length * 8} cross-brand accents against every surface`,
  );
}

if (drift) {
  console.error(`\n${drift} generated file(s) out of sync. Run: node scripts/build-tokens.mjs`);
}

// One verdict, written to the stream that carries the detail, because a shell showing stdout and
// stderr as separate blocks will otherwise end a failed run with "contrast gate passed".
if (allFailures.length || drift) {
  console.error(
    `\nFAILED: ${allFailures.length} contrast failure(s), ${drift} file(s) out of sync.`,
  );
  process.exit(1);
}
