/* GENERATED by web-kit/packages/brand/scripts/build-tokens.mjs from tokens.json.
   Do not hand-edit tags.ts. Change tokens.json and rebuild.
   Contract: Infra/docs/UX-STANDARD.md */

/** The generated tag tones, in palette order. Index 0 is the neutral 'no category' swatch. */
export const TAG_TONES = [
  "neutral",
  "red",
  "rose",
  "pink",
  "fuchsia",
  "violet",
  "indigo",
  "blue",
  "cyan",
  "teal",
  "green",
  "lime",
  "yellow",
  "ochre",
  "clay",
] as const;

export type TagTone = (typeof TAG_TONES)[number];

/**
 * Picks a stable swatch for a piece of text: a sender, a label, a tenant. The same
 * name is always the same colour, without storing a colour per record.
 *
 * Must stay identical to `pxTagFor` in prabhix_tokens.dart.
 */
export function toneFor(seed: string): TagTone {
  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) {
    hash = (hash * 31 + seed.charCodeAt(i)) & 0x1fffffff;
  }
  // Skips index 0, the neutral swatch, which is reserved for 'no category'.
  return TAG_TONES[1 + (hash % (TAG_TONES.length - 1))];
}
